#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Point luarocks at Neovim's LuaJIT (Lua 5.1) so
#   luarocks --lua-version 5.1 --local install <rock>
# builds rocks that Neovim (LuaJIT) can require() and that lua_ls can index,
# then install the rocks declared in the Neovim Rockfile manifest.

if ! command -v brew >/dev/null 2>&1; then
	echo "⏭  brew not found — skipping luarocks 5.1 config"
	exit 0
fi

LUAJIT_PREFIX="$(brew --prefix luajit 2>/dev/null || true)"
if [[ -z "$LUAJIT_PREFIX" || ! -x "$LUAJIT_PREFIX/bin/luajit" ]]; then
	echo "⏭  luajit not installed — skipping luarocks 5.1 config"
	exit 0
fi

# LuaJIT keeps its headers under include/luajit-2.1 rather than include/.
LUA_H="$(find "$LUAJIT_PREFIX/include" -name lua.h 2>/dev/null | head -n1)"
if [[ -z "$LUA_H" ]]; then
	echo "⚠️  Could not locate LuaJIT lua.h under $LUAJIT_PREFIX/include — skipping"
	exit 0
fi
LUA_INCDIR="$(dirname "$LUA_H")"

CFG="$HOME/.luarocks/config-5.1.lua"
mkdir -p "$(dirname "$CFG")"

cat >"$CFG" <<EOF
-- Generated by scripts/luarocks.sh — targets Neovim's LuaJIT (Lua 5.1).
lua_version = "5.1"
lua_interpreter = "luajit"
variables = {
   LUA = "$LUAJIT_PREFIX/bin/luajit",
   LUA_BINDIR = "$LUAJIT_PREFIX/bin",
   LUA_INCDIR = "$LUA_INCDIR",
}
EOF

echo "✅ luarocks 5.1 config written: $CFG"
echo "   LuaJIT: $LUAJIT_PREFIX"

# --- Install rocks declared in the Neovim Rockfile manifest (column 1 = rock name) ---
ROCKFILE="$SCRIPT_DIR/../nvim/.config/nvim/Rockfile"
if ! command -v luarocks >/dev/null 2>&1; then
	echo "⏭  luarocks not found — skipping rock installs"
	exit 0
fi
if [[ ! -f "$ROCKFILE" ]]; then
	echo "⏭  no Rockfile at $ROCKFILE — nothing to install"
	exit 0
fi

echo "🪨 Installing rocks from $ROCKFILE"
while read -r rock _; do
	[[ -z "$rock" || "$rock" == \#* ]] && continue
	if luarocks --lua-version 5.1 list --porcelain "$rock" 2>/dev/null | grep -q .; then
		echo "   ✅ $rock already installed"
	else
		echo "   ⬇️  installing $rock"
		luarocks --lua-version 5.1 --local install "$rock" || echo "   ⚠️  Failed to install rock: $rock"
	fi
done <"$ROCKFILE"
