return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  branch = "main",
  lazy = false,
  config = function()
    vim.opt.foldmethod = "expr"
    vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"

    local parsers = {
      "astro",
      "bash",
      "c",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "editorconfig",
      "fish",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "groovy",
      "hcl",
      "hocon",
      "html",
      "http",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "kdl",
      "kotlin",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "proto",
      "python",
      "query",
      "regex",
      "ruby",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "styled",
      "svelte",
      "templ",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
      "zig",
    }

    require("nvim-treesitter").install(parsers)
    vim.api.nvim_create_autocmd("FileType", {
      pattern = parsers,
      callback = function(args)
        vim.treesitter.start()
      end,
    })
  end,
  opts = {
    ensure_installed = {
      "go",
      "gomod",
      "gosum",
      "gowork",
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "toml",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        scope_incremental = false,
        init_selection = "<M-space>",
        node_incremental = "<M-space>",
        node_decremental = "<BS>",
      },
    },
    textobjects = {
      move = {
        enable = true,
        goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer", ["]a"] = "@parameter.inner" },
        goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer", ["]A"] = "@parameter.inner" },
        goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer", ["[a"] = "@parameter.inner" },
        goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer", ["[A"] = "@parameter.inner" },
      },
    },
  },
}
