return {
  {
    "arborist-ts/arborist.nvim",
    lazy = false,
    config = function()
      vim.opt.foldmethod = "expr"
      vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"

      require("arborist").setup({
        ensure_installed = {
          "bash",
          "c",
          "css",
          "csv",
          "diff",
          "dockerfile",
          "editorconfig",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "go",
          "gomod",
          "gosum",
          "gotmpl",
          "gowork",
          "html",
          "http",
          "javascript",
          "jsdoc",
          "json",
          "lua",
          "luadoc",
          "luap",
          "markdown",
          "markdown_inline",
          "python",
          "query",
          "regex",
          "scss",
          "sql",
          "ssh_config",
          "styled",
          "templ",
          "toml",
          "tsx",
          "typescript",
          "vim",
          "vimdoc",
          "yaml",
          "zig",
        },
      })
    end,
  },
}
